21points-elasticsearch:
  container_name: 21points-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/21points/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
21points-postgresql:
  container_name: 21points-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/21points/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=21points
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
